#ifndef WX_INSPECTOR_VERSION_H
#define WX_INSPECTOR_VERSION_H

#define WX_INSPECTOR_MAJOR_VERSION 1
#define WX_INSPECTOR_MINOR_VERSION 0
#define WX_INSPECTOR_PATCH_VERSION 0
#define WX_INSPECTOR_VERSION_STRING "wxInspector 1.0.0"

#endif // WX_INSPECTOR_VERSION_H